
version: '3'
services:
  server:
    build: server/
    command: ./bin/pravega-standalone
    network_mode: host
    ports: 
      - 1234:1234
       
  client:
    build: client/
    command: python3 ./read.py  
    network_mode: host
    depends_on:
      - server  

